-- MySQL Script generated by MySQL Workbench
-- 10/23/24 23:11:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sehc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sehc` DEFAULT CHARACTER SET utf8 ;
USE `sehc` ;

-- -----------------------------------------------------
-- Table `sehc`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sehc`.`client` (
  `idclient` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idclient`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idclient` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sehc`.`invoice_client_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sehc`.`invoice_client_data` (
  `idinvoice_client_data` INT NOT NULL,
  `client_idclient` INT(11) NOT NULL,
  `socialReazon` VARCHAR(100) NULL,
  `zipCode` VARCHAR(10) NULL,
  `fiscalRegimen` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idinvoice_client_data`),
  UNIQUE INDEX `idinvoice_client_data_UNIQUE` (`idinvoice_client_data` ASC),
  INDEX `fk_invoice_client_data_client_idx` (`client_idclient` ASC),
  CONSTRAINT `fk_invoice_client_data_client`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `sehc`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sehc` ;

-- -----------------------------------------------------
-- Table `sehc`.`priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sehc`.`priority` (
  `idpriority` INT(11) NOT NULL,
  `priority` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idpriority`),
  UNIQUE INDEX `idpriority_UNIQUE` (`idpriority` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sehc`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sehc`.`user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sehc`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sehc`.`vehicle` (
  `idVehicle` INT(11) NOT NULL,
  `cliente_idcliente` INT(11) NOT NULL,
  `brand` VARCHAR(45) NULL DEFAULT NULL,
  `model` VARCHAR(45) NULL DEFAULT NULL,
  `year` VARCHAR(45) NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `plate` VARCHAR(45) NULL DEFAULT NULL,
  `doors` INT(2) NULL DEFAULT NULL,
  `motor` VARCHAR(45) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idVehicle`),
  UNIQUE INDEX `idVehicle_UNIQUE` (`idVehicle` ASC),
  INDEX `fk_vehicle_cliente1_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_vehicle_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `sehc`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sehc`.`service_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sehc`.`service_status` (
  `idservice_status` INT(11) NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idservice_status`),
  UNIQUE INDEX `idservice_status_UNIQUE` (`idservice_status` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sehc`.`service_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sehc`.`service_type` (
  `idservice_type` INT(11) NOT NULL,
  `service` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idservice_type`),
  UNIQUE INDEX `idservice_type_UNIQUE` (`idservice_type` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sehc`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sehc`.`service` (
  `idService` INT(11) NOT NULL,
  `Vehicle_idVehicle` INT(11) NOT NULL,
  `User_idUser` INT(11) NOT NULL,
  `service_status_idservice_status` INT(11) NOT NULL,
  `service_type_idservice_type` INT(11) NOT NULL,
  `priority_idpriority` INT(11) NOT NULL,
  `diagnostic` VARCHAR(2000) NULL DEFAULT NULL,
  `gasLevel` VARCHAR(45) NULL DEFAULT NULL,
  `km` VARCHAR(45) NULL DEFAULT NULL,
  `serviceDetails` JSON NULL DEFAULT NULL,
  `totalCost` VARCHAR(45) NULL DEFAULT NULL,
  `serviceNotes` VARCHAR(1000) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idService`),
  UNIQUE INDEX `idService_UNIQUE` (`idService` ASC),
  INDEX `fk_Service_Vehicle1_idx` (`Vehicle_idVehicle` ASC),
  INDEX `fk_Service_User1_idx` (`User_idUser` ASC),
  INDEX `fk_service_service_status1_idx` (`service_status_idservice_status` ASC),
  INDEX `fk_service_service_type1_idx` (`service_type_idservice_type` ASC),
  INDEX `fk_service_priority1_idx` (`priority_idpriority` ASC),
  CONSTRAINT `fk_Service_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `sehc`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Vehicle1`
    FOREIGN KEY (`Vehicle_idVehicle`)
    REFERENCES `sehc`.`vehicle` (`idVehicle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_priority1`
    FOREIGN KEY (`priority_idpriority`)
    REFERENCES `sehc`.`priority` (`idpriority`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_service_status1`
    FOREIGN KEY (`service_status_idservice_status`)
    REFERENCES `sehc`.`service_status` (`idservice_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_service_type1`
    FOREIGN KEY (`service_type_idservice_type`)
    REFERENCES `sehc`.`service_type` (`idservice_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- these inserts can be modified if required to match with the workshop requirements

-- -----------------------------------------------------
-- Default inserts for table `sehc`.`priority`
-- -----------------------------------------------------

INSERT INTO `sehc`.`priority` (`idpriority`, `priority`) VALUES ('1', 'Baja');
INSERT INTO `sehc`.`priority` (`idpriority`, `priority`) VALUES ('2', 'Media');
INSERT INTO `sehc`.`priority` (`idpriority`, `priority`) VALUES ('3', 'Alta');
INSERT INTO `sehc`.`priority` (`idpriority`, `priority`) VALUES ('4', 'Critica');

-- -----------------------------------------------------
-- Default inserts for table `sehc`.`service_status`
-- -----------------------------------------------------
INSERT INTO `sehc`.`service_status` (`idservice_status`, `status`) VALUES ('1', 'En espera');
INSERT INTO `sehc`.`service_status` (`idservice_status`, `status`) VALUES ('2', 'Asignado');
INSERT INTO `sehc`.`service_status` (`idservice_status`, `status`) VALUES ('3', 'En proceso');
INSERT INTO `sehc`.`service_status` (`idservice_status`, `status`) VALUES ('4', 'Terminado');
INSERT INTO `sehc`.`service_status` (`idservice_status`, `status`) VALUES ('5', 'Entregado');

-- -----------------------------------------------------
-- Default inserts fro table `sehc`.`service_type`
-- -----------------------------------------------------
INSERT INTO `sehc`.`service_type` (`idservice_type`, `service`) VALUES ('1', 'Chequeo general');
INSERT INTO `sehc`.`service_type` (`idservice_type`, `service`) VALUES ('2', 'Reparacion');
INSERT INTO `sehc`.`service_type` (`idservice_type`, `service`) VALUES ('3', 'Garantia');
