-- MySQL Script generated by MySQL Workbench
-- 10/04/24 21:10:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SEHC
-- -----------------------------------------------------
-- Database for Servicio Especializado Honda Control

-- -----------------------------------------------------
-- Schema SEHC
--
-- Database for Servicio Especializado Honda Control
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SEHC` ;
USE `SEHC` ;

-- -----------------------------------------------------
-- Table `SEHC`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SEHC`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SEHC`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SEHC`.`Vehicle` (
  `idVehicle` INT NOT NULL,
  `brand` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `year` VARCHAR(45) NULL,
  `plate` VARCHAR(45) NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idVehicle`),
  UNIQUE INDEX `idVehicle_UNIQUE` (`idVehicle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SEHC`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SEHC`.`Service` (
  `idService` INT NOT NULL,
  `serviceType` VARCHAR(45) NULL,
  `serviceDetails` JSON NULL,
  `serviceDate` TIMESTAMP NULL,
  `serviceStatus` VARCHAR(45) NULL,
  `totalCost` VARCHAR(45) NULL,
  `serviceNotes` VARCHAR(1000) NULL,
  `Vehicle_idVehicle` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idService`),
  UNIQUE INDEX `idService_UNIQUE` (`idService` ASC),
  INDEX `fk_Service_Vehicle1_idx` (`Vehicle_idVehicle` ASC),
  INDEX `fk_Service_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Service_Vehicle1`
    FOREIGN KEY (`Vehicle_idVehicle`)
    REFERENCES `SEHC`.`Vehicle` (`idVehicle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `SEHC`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
